import type { BankStagingRow } from '@/lib/types'

export const MOCK_BANK_TRANSACTIONS: BankStagingRow[] = [
  // ── Posted rows ───────────────────────────────────────────────────────────────
  {
    id: 1,
    comcode: 'ZeniroxPay',
    date: '2025-01-01',
    journalType: 'Bank fee',
    docNum: '202501.1019512.1',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 1.00,
    partnerCode: 'Bank of CAN',
    description: 'Monthly bank service fee',
    balanceImpact: 'Debit',
    refTxnId: 'xxx',
    refNum: 'xxx',
    xrate: null,
    datasource: 'BankCAN',
    glPosted: true,
  },
  {
    id: 2,
    comcode: 'ZeniroxPay',
    date: '2025-01-02',
    journalType: 'OverdraftInterest',
    docNum: '202501.1019512.2',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 2.00,
    partnerCode: 'Bank of CAN',
    description: 'Overdraft interest charge',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: true,
  },
  // ── Unposted rows ─────────────────────────────────────────────────────────────
  {
    id: 3,
    comcode: 'ZeniroxPay',
    date: '2025-01-03',
    journalType: 'Consulting fee',
    docNum: '202501.1019512.3',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 3.00,
    partnerCode: 'BPTax',
    description: 'Tax consulting services',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 4,
    comcode: 'ZeniroxPay',
    date: '2025-01-04',
    journalType: 'Management fee',
    docNum: '202501.1019512.4',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 4.00,
    partnerCode: 'OfficeOwner',
    description: 'Office management fee Jan 2025',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 5,
    comcode: 'ZeniroxPay',
    date: '2025-01-05',
    journalType: 'Transfer from PayPal',
    docNum: '202501.1019512.4',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 5.00,
    partnerCode: 'ZeniroxPay',
    description: 'PayPal withdrawal to bank',
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 6,
    comcode: 'ZeniroxPay',
    date: '2025-01-06',
    journalType: 'Transfer to PayPal',
    docNum: '202501.1019512.4',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 3.00,
    partnerCode: 'ZeniroxPay',
    description: 'Bank transfer to PayPal account',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 7,
    comcode: 'ZeniroxPay',
    date: '2025-01-10',
    journalType: 'Payroll',
    docNum: '202501.1019512.5',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 8500.00,
    partnerCode: 'Staff',
    description: 'January 2025 payroll',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 8,
    comcode: 'ZeniroxPay',
    date: '2025-01-15',
    journalType: 'Rent expense',
    docNum: '202501.1019512.6',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 2200.00,
    partnerCode: 'Landlord Inc',
    description: 'Office rent Jan 2025',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 9,
    comcode: 'ZeniroxPay',
    date: '2025-01-20',
    journalType: 'Interest income',
    docNum: '202501.1019512.7',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 45.50,
    partnerCode: 'Bank of CAN',
    description: 'Savings account interest',
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 10,
    comcode: 'ZeniroxPay',
    date: '2025-01-25',
    journalType: 'Supplier payment',
    docNum: '202501.1019512.8',
    bankAccountNum: '1019512',
    period: '202501',
    currency: 'CAD',
    amount: 12300.00,
    partnerCode: 'GlobalShip Ltd',
    description: 'Freight charges Q4 2024 settlement',
    balanceImpact: 'Debit',
    refTxnId: 'INV-2024-0892',
    refNum: 'PO-8822',
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
]
