import type { PaypalStagingRow } from '@/lib/types'

export const MOCK_PAYPAL_TRANSACTIONS: PaypalStagingRow[] = [
  // ── Bulk rows (đã ghi sổ) ──────────────────────────────────────────────────
  {
    id: 1,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Express Checkout Payment',
    docNum: '202501.Express Checkout Payment.Individuals.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 12354.12,
    fee: -1.00,
    net: 12353.12,
    transactionId: 'TXN-2025-0001',
    partnerCode: 'Individuals',
    description: '202501.Express Checkout Payment.Individuals',
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: true,
  },
  {
    id: 2,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Chargeback Fee',
    docNum: '202501.Chargeback Fee.Individuals.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 1235.30,
    fee: -2.00,
    net: 1233.30,
    transactionId: 'TXN-2025-0002',
    partnerCode: 'Individuals',
    description: '202501.Chargeback Fee.Individuals',
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: true,
  },
  // ── Bulk rows (chưa ghi sổ) ────────────────────────────────────────────────
  {
    id: 3,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Direct Credit Card Payment',
    docNum: '202501.Direct Credit Card Payment.Individuals.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 36560.00,
    fee: -1.00,
    net: 36559.00,
    transactionId: 'TXN-2025-0003',
    partnerCode: 'Individuals',
    description: '202501.Direct Credit Card Payment.Individuals',
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 4,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Chargeback',
    docNum: '202501.Chargeback.Individuals.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 3656.00,
    fee: -1.00,
    net: 3655.00,
    transactionId: 'TXN-2025-0004',
    partnerCode: 'Individuals',
    description: '202501.Chargeback.Individuals',
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 5,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Payment Refund',
    docNum: '202501.Payment Refund.Individuals.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 14123.00,
    fee: -1.00,
    net: 14122.00,
    transactionId: 'TXN-2025-0005',
    partnerCode: 'Individuals',
    description: '202501.Payment Refund.Individuals',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 6,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Reserve Hold',
    docNum: '202501.Reserve Hold.PAYPAL.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 1234.12,
    fee: 0.00,
    net: 1234.12,
    transactionId: 'TXN-2025-0006',
    partnerCode: 'PAYPAL',
    description: '202501.Reserve Hold.PAYPAL',
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 7,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Reserve Release',
    docNum: '202501.Reserve Release.PAYPAL.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 123.34,
    fee: 0.00,
    net: 123.34,
    transactionId: 'TXN-2025-0007',
    partnerCode: 'PAYPAL',
    description: '202501.Reserve Release.PAYPAL',
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 8,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Dispute Fee',
    docNum: '202501.Dispute Fee.Individuals.= STK PAYPAL',
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 325.00,
    fee: -1.00,
    net: 324.00,
    transactionId: 'TXN-2025-0008',
    partnerCode: 'Individuals',
    description: '202501.Dispute Fee.Individuals',
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Bulk',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  // ── Single rows (chưa ghi sổ — template/individual transactions) ───────────
  {
    id: 9,
    comcode: 'ZeniroxPay',
    date: '2025-01-15',
    journalType: 'General Authorization',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 250.00,
    fee: -7.35,
    net: 242.65,
    transactionId: 'TXN-2025-0009',
    partnerCode: null,
    description: null,
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 10,
    comcode: 'ZeniroxPay',
    date: '2025-01-16',
    journalType: 'General Currency Conversion',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 500.00,
    fee: 0.00,
    net: 500.00,
    transactionId: 'TXN-2025-0010',
    partnerCode: null,
    description: null,
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 11,
    comcode: 'ZeniroxPay',
    date: '2025-01-20',
    journalType: 'Hold on Available Balance',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 1000.00,
    fee: 0.00,
    net: 1000.00,
    transactionId: 'TXN-2025-0011',
    partnerCode: null,
    description: null,
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 12,
    comcode: 'ZeniroxPay',
    date: '2025-01-22',
    journalType: 'Mass Pay Payment',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: -3500.00,
    fee: -1.00,
    net: -3501.00,
    transactionId: 'TXN-2025-0012',
    partnerCode: null,
    description: null,
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 13,
    comcode: 'ZeniroxPay',
    date: '2025-01-25',
    journalType: 'Mass Payment',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: -800.00,
    fee: 0.00,
    net: -800.00,
    transactionId: 'TXN-2025-0013',
    partnerCode: null,
    description: null,
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 14,
    comcode: 'ZeniroxPay',
    date: '2025-01-26',
    journalType: 'Partner Fee',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: -15.00,
    fee: 0.00,
    net: -15.00,
    transactionId: 'TXN-2025-0014',
    partnerCode: null,
    description: null,
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 15,
    comcode: 'ZeniroxPay',
    date: '2025-01-28',
    journalType: 'Payment Review',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 450.00,
    fee: -13.05,
    net: 436.95,
    transactionId: 'TXN-2025-0015',
    partnerCode: null,
    description: null,
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 16,
    comcode: 'ZeniroxPay',
    date: '2025-01-29',
    journalType: 'Reversal of General Account Hold',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: 200.00,
    fee: 0.00,
    net: 200.00,
    transactionId: 'TXN-2025-0016',
    partnerCode: null,
    description: null,
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
  {
    id: 17,
    comcode: 'ZeniroxPay',
    date: '2025-01-30',
    journalType: 'User Initiated Withdrawal',
    docNum: null,
    bankAccountNum: 'STK PAYPAL',
    period: '202501',
    currency: 'USD',
    gross: -5000.00,
    fee: 0.00,
    net: -5000.00,
    transactionId: 'TXN-2025-0017',
    partnerCode: null,
    description: null,
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    classify: 'Single',
    datasource: 'PAYPAL',
    glPosted: false,
  },
]
