import type { ThemeConfig } from "antd"

export const COLORS = {
  majorelleBlue: {
    1: "#EEEDFF",
    2: "#D6D4FE",
    3: "#B5B0FC",
    4: "#948CFC",
    5: "#746BFA",
    6: "#574CFA",
    7: "#4941D4",
    8: "#3E36B2",
    9: "#312B8E",
    10: "#272171",
  },
  blue: {
    1: "#E6F4FF",
    2: "#BAE0FF",
    3: "#91CAFF",
    4: "#69B1FF",
    5: "#4096FF",
    6: "#1677FF",
    7: "#0958D9",
    8: "#003EB3",
    9: "#002C8C",
    10: "#001D66",
  },
  cyan: {
    1: "#E6FFFB",
    2: "#B5F5EC",
    3: "#87E8DE",
    4: "#5CDBD3",
    5: "#36CFC9",
    6: "#13C2C2",
    7: "#08979C",
    8: "#006D75",
    9: "#00474F",
    10: "#002329",
  },
  geekBlue: {
    1: "#F0F5FF",
    2: "#D6E4FF",
    3: "#ADC6FF",
    4: "#85A5FF",
    5: "#597EF7",
    6: "#2F54EB",
    7: "#1D39C4",
    8: "#10239E",
    9: "#061178",
    10: "#030852",
  },
  gold: {
    1: "#FFFBE6",
    2: "#FFF1B8",
    3: "#FFE58F",
    4: "#FFD666",
    5: "#FFC53D",
    6: "#FAAD14",
    7: "#D48806",
    8: "#AD6800",
    9: "#874D00",
    10: "#613400",
  },
  green: {
    1: "#ECF7F1",
    2: "#D0EDDC",
    3: "#ABDEC1",
    4: "#84CEA4",
    5: "#5FC088",
    6: "#3CB26E",
    7: "#33975E",
    8: "#2B7E4E",
    9: "#22653F",
    10: "#1B5031",
  },
  lime: {
    1: "#FCFFE6",
    2: "#F4FFB8",
    3: "#EAFF8F",
    4: "#D3F261",
    5: "#BAE637",
    6: "#A0D911",
    7: "#7CB305",
    8: "#5B8C00",
    9: "#3F6600",
    10: "#254000",
  },
  magenta: {
    1: "#FFF0F6",
    2: "#FFD6E7",
    3: "#FFADD2",
    4: "#FF85C0",
    5: "#F759AB",
    6: "#EB2F96",
    7: "#C41D7F",
    8: "#9E1068",
    9: "#780650",
    10: "#520339",
  },
  orange: {
    1: "#FFF7E6",
    2: "#FFE7BA",
    3: "#FFD591",
    4: "#FFC069",
    5: "#FFA940",
    6: "#FA8C16",
    7: "#D46B08",
    8: "#AD4E00",
    9: "#873800",
    10: "#612500",
  },
  purple: {
    1: "#F9F0FF",
    2: "#EFDBFF",
    3: "#D3ADF7",
    4: "#B37FEB",
    5: "#9254DE",
    6: "#722ED1",
    7: "#531DAB",
    8: "#391085",
    9: "#22075E",
    10: "#120338",
  },
  red: {
    1: "#FFF1F0",
    2: "#FFCCC7",
    3: "#FFA39E",
    4: "#FF7875",
    5: "#FF4D4F",
    6: "#F5222D",
    7: "#CF1322",
    8: "#A8071A",
    9: "#820014",
    10: "#5C0011",
    11: "#990000",
  },
  volcano: {
    1: "#FFF2E8",
    2: "#FFD8BF",
    3: "#FFBB96",
    4: "#FF9C6E",
    5: "#FF7A45",
    6: "#FA541C",
    7: "#D4380D",
    8: "#AD2102",
    9: "#871400",
    10: "#610B00",
  },
  yellow: {
    1: "#FEFFE6",
    2: "#FFFFB8",
    3: "#FFFB8F",
    4: "#FFF566",
    5: "#FFEC3D",
    6: "#FADB14",
    7: "#D4B106",
    8: "#AD8B00",
    9: "#876800",
    10: "#614700",
  },
}

export const NEUTRAL_COLORS_BASE = {
  text: {
    base: "#1D1D1D",
    secondary: "#535353",
    tertiary: "#828282",
    quaternary: "#B2B2B2",
    lightSolid: "#FFFFFF",
  },
  background: {
    base: "#FFFFFF",
    layout: "#F5F5F5",
    mask: "#00000073",
    sportLight: "#000000D9",
  },
  border: {
    base: "#D9D9D9",
    secondary: "#F0F0F0",
    split: "#0000000F",
  },
  fill: {
    base: "#00000026",
    secondary: "#0000000F",
    tertiary: "#0000000A",
    quaternary: "#00000005",
  },
}

export const NEUTRAL_COLORS = {
  text: {
    colorText: NEUTRAL_COLORS_BASE.text.base,
    colorTextSecondary: NEUTRAL_COLORS_BASE.text.secondary,
    colorTextTertiary: NEUTRAL_COLORS_BASE.text.tertiary,
    colorTextQuaternary: NEUTRAL_COLORS_BASE.text.quaternary,
    colorTextLightSolid: NEUTRAL_COLORS_BASE.text.lightSolid,
    colorTextHeading: NEUTRAL_COLORS_BASE.text.base,
    colorTextLabel: NEUTRAL_COLORS_BASE.text.secondary,
    colorTextDescription: NEUTRAL_COLORS_BASE.text.tertiary,
    colorTextDisabled: NEUTRAL_COLORS_BASE.text.quaternary,
    colorTextPlaceholder: NEUTRAL_COLORS_BASE.text.quaternary,
  },
  icon: {
    colorIconPrimary: NEUTRAL_COLORS_BASE.text.base,
    colorIconSecondary: NEUTRAL_COLORS_BASE.text.secondary,
    colorIconDisable: NEUTRAL_COLORS_BASE.text.quaternary,
    colorIconHover: NEUTRAL_COLORS_BASE.text.base,
  },
  background: {
    colorBgContainer: NEUTRAL_COLORS_BASE.background.base,
    colorBgElevated: NEUTRAL_COLORS_BASE.background.base,
    colorBgLayout: NEUTRAL_COLORS_BASE.background.layout,
    colorBgMask: NEUTRAL_COLORS_BASE.background.mask,
    colorBgSpotlight: NEUTRAL_COLORS_BASE.background.sportLight,
    colorBgContainerDisabled: NEUTRAL_COLORS_BASE.fill.tertiary,
    colorBgTextActive: NEUTRAL_COLORS_BASE.fill.base,
    colorBgTextHover: NEUTRAL_COLORS_BASE.fill.secondary,
    colorBorderBg: NEUTRAL_COLORS_BASE.background.base,
  },
  border: {
    colorBorder: NEUTRAL_COLORS_BASE.border.base,
    colorBorderSecondary: NEUTRAL_COLORS_BASE.border.secondary,
    colorSplit: NEUTRAL_COLORS_BASE.border.split,
  },
  fill: {
    colorFill: NEUTRAL_COLORS_BASE.fill.base,
    colorFillSecondary: NEUTRAL_COLORS_BASE.fill.secondary,
    colorFillTertiary: NEUTRAL_COLORS_BASE.fill.tertiary,
    colorFillQuaternary: NEUTRAL_COLORS_BASE.fill.quaternary,
    colorFillContent: NEUTRAL_COLORS_BASE.fill.secondary,
    colorFillContentHover: NEUTRAL_COLORS_BASE.fill.base,
    colorFillAlter: NEUTRAL_COLORS_BASE.fill.quaternary,
    colorFillAlterSolid: "#FAFAFA",
  },
}

export const BRAND_COLORS = {
  primary: {
    colorPrimaryBg: COLORS.majorelleBlue["1"],
    colorPrimaryBgHover: COLORS.majorelleBlue["2"],
    colorPrimaryBorder: COLORS.majorelleBlue["3"],
    colorPrimaryBorderHover: COLORS.majorelleBlue["4"],
    colorPrimaryHover: COLORS.majorelleBlue["5"],
    colorPrimary: COLORS.majorelleBlue["6"],
    colorPrimaryActive: COLORS.majorelleBlue["7"],
    colorPrimaryTextHover: COLORS.majorelleBlue["5"],
    colorPrimaryText: COLORS.majorelleBlue["6"],
    colorPrimaryTextActive: COLORS.majorelleBlue["7"],
  },
  success: {
    colorSuccessBg: COLORS.green["1"],
    colorSuccessBgHover: COLORS.green["2"],
    colorSuccessBorder: COLORS.green["3"],
    colorSuccessBorderHover: COLORS.green["4"],
    colorSuccessHover: COLORS.green["4"],
    colorSuccess: COLORS.green["6"],
    colorSuccessActive: COLORS.green["7"],
    colorSuccessTextHover: COLORS.green["5"],
    colorSuccessText: COLORS.green["6"],
    colorSuccessTextActive: COLORS.green["7"],
  },
  warning: {
    colorWarningBg: COLORS.gold["1"],
    colorWarningBgHover: COLORS.gold["2"],
    colorWarningBorder: COLORS.gold["3"],
    colorWarningBorderHover: COLORS.gold["4"],
    colorWarningHover: COLORS.gold["4"],
    colorWarning: COLORS.gold["6"],
    colorWarningActive: COLORS.gold["7"],
    colorWarningTextHover: COLORS.gold["5"],
    colorWarningText: COLORS.gold["6"],
    colorWarningTextActive: COLORS.gold["7"],
    colorWarningOutline: "#FFD7051A",
  },
  info: {
    colorInfoBg: COLORS.majorelleBlue["1"],
    colorInfoBgHover: COLORS.majorelleBlue["2"],
    colorInfoBorder: COLORS.majorelleBlue["3"],
    colorInfoBorderHover: COLORS.majorelleBlue["4"],
    colorInfoHover: COLORS.majorelleBlue["5"],
    colorInfo: COLORS.majorelleBlue["6"],
    colorInfoActive: COLORS.majorelleBlue["7"],
    colorInfoTextHover: COLORS.majorelleBlue["5"],
    colorInfoText: COLORS.majorelleBlue["6"],
    colorInfoTextActive: COLORS.majorelleBlue["7"],
  },
  error: {
    colorErrorBg: COLORS.red["1"],
    colorErrorBgHover: COLORS.red["2"],
    colorErrorBorder: COLORS.red["3"],
    colorErrorBorderHover: COLORS.red["4"],
    colorErrorHover: COLORS.red["4"],
    colorError: COLORS.red["6"],
    colorErrorActive: COLORS.red["8"],
    colorErrorTextHover: COLORS.red["5"],
    colorErrorText: COLORS.red["6"],
    colorErrorTextActive: COLORS.red["8"],
    colorErrorOutline: "#FF26060F",
  },
  link: {
    colorLink: COLORS.majorelleBlue[6],
    colorLinkHover: COLORS.majorelleBlue[5],
    colorLinkActive: COLORS.majorelleBlue[7],
  },
  control: {
    controlItemBgActive: COLORS.majorelleBlue["1"],
    controlItemBgActiveDisabled: NEUTRAL_COLORS_BASE.fill.base,
    controlItemBgActiveHover: COLORS.majorelleBlue["2"],
    controlItemBgHover: NEUTRAL_COLORS_BASE.fill.tertiary,
    controlOutline: "#574CFA1A",
    controlTmpOutline: NEUTRAL_COLORS_BASE.fill.quaternary,
  },
}

export const TYPOGRAPHY = {
  base: {
    fontSize: 14,
    lineHeight: 22,
  },
  sm: {
    fontSize: 12,
    lineHeight: 20,
  },
  lg: {
    fontSize: 16,
    lineHeight: 24,
  },
  "leading-1": {
    fontSize: 38,
    lineHeight: 46,
  },
  "leading-2": {
    fontSize: 30,
    lineHeight: 38,
  },
  "leading-3": {
    fontSize: 24,
    lineHeight: 32,
  },
  "leading-4": {
    fontSize: 20,
    lineHeight: 28,
  },
  "leading-5": {
    fontSize: 16,
    lineHeight: 24,
  },
}

export const themeConfig: ThemeConfig = {
  token: {
    // Primary
    ...BRAND_COLORS.primary,
    // Success
    ...BRAND_COLORS.success,
    // Warning
    ...BRAND_COLORS.warning,
    // Info
    ...BRAND_COLORS.info,
    // Error
    ...BRAND_COLORS.error,
    // Link
    ...BRAND_COLORS.link,
    // Control
    ...BRAND_COLORS.control,

    // Text
    ...NEUTRAL_COLORS.text,
    // Icon
    ...NEUTRAL_COLORS.icon,
    // background
    ...NEUTRAL_COLORS.background,
    // border
    ...NEUTRAL_COLORS.border,
    // fill
    ...NEUTRAL_COLORS.fill,

    fontSizeSM: TYPOGRAPHY.sm.fontSize,
    // lineHeightSM: TYPOGRAPHY.sm.lineHeight,

    fontSize: TYPOGRAPHY.base.fontSize,
    // lineHeight: TYPOGRAPHY.base.lineHeight,

    fontSizeLG: TYPOGRAPHY.lg.fontSize,
    // lineHeightLG: TYPOGRAPHY.lg.lineHeight,

    fontSizeHeading1: TYPOGRAPHY["leading-1"].fontSize,
    // lineHeightHeading1: TYPOGRAPHY["leading-1"].lineHeight,

    fontSizeHeading2: TYPOGRAPHY["leading-2"].fontSize,
    // lineHeightHeading2: TYPOGRAPHY["leading-2"].lineHeight,

    fontSizeHeading3: TYPOGRAPHY["leading-3"].fontSize,
    // lineHeightHeading3: TYPOGRAPHY["leading-3"].lineHeight,

    fontSizeHeading4: TYPOGRAPHY["leading-4"].fontSize,
    // lineHeightHeading4: TYPOGRAPHY["leading-4"].lineHeight,

    fontSizeHeading5: TYPOGRAPHY["leading-5"].fontSize,
    // lineHeightHeading5: TYPOGRAPHY["leading-5"].lineHeight,
  },
}
