import type { BettamaxStagingRow } from '@/lib/types'

export const MOCK_BETTAMAX_TRANSACTIONS: BettamaxStagingRow[] = [
  // ── Bulk rows (đã ghi sổ) ──────────────────────────────────────────────────
  {
    id: 1,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'Sales of Goods',
    docNum: '202501.Sales of Goods.Individuals',
    period: '202501',
    currency: 'USD',
    amount: 12354.12,
    xrate: null,
    partnerCode: 'Individuals',
    datasource: 'Platform',
    glPosted: true,
  },
  {
    id: 2,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'ShippingRev',
    docNum: '202501.ShippingRev.Individuals',
    period: '202501',
    currency: 'USD',
    amount: 232.00,
    xrate: null,
    partnerCode: 'Individuals',
    datasource: 'Platform',
    glPosted: true,
  },
  {
    id: 3,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'AdditionalRev',
    docNum: '202501.AdditionalRev.Individuals',
    period: '202501',
    currency: 'USD',
    amount: 321.00,
    xrate: null,
    partnerCode: 'Individuals',
    datasource: 'Platform',
    glPosted: true,
  },
  {
    id: 4,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'Taxfee',
    docNum: '202501.Taxfee.Individuals',
    period: '202501',
    currency: 'USD',
    amount: 1235.30,
    xrate: null,
    partnerCode: 'Individuals',
    datasource: 'Platform',
    glPosted: true,
  },
  // ── SellerCost rows (chưa ghi sổ) ─────────────────────────────────────────
  {
    id: 5,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'SellerCost',
    docNum: '202501.SellerCost.Store1',
    period: '202501',
    currency: 'USD',
    amount: 1234.12,
    xrate: null,
    partnerCode: 'Store1',
    datasource: 'Platform',
    glPosted: false,
  },
  {
    id: 6,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'SellerCost',
    docNum: '202501.SellerCost.Store2',
    period: '202501',
    currency: 'USD',
    amount: 123.34,
    xrate: null,
    partnerCode: 'Store2',
    datasource: 'Platform',
    glPosted: false,
  },
  {
    id: 7,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'SellerCost',
    docNum: '202501.SellerCost.Store3',
    period: '202501',
    currency: 'USD',
    amount: 325.00,
    xrate: null,
    partnerCode: 'Store3',
    datasource: 'Platform',
    glPosted: false,
  },
  // ── SupplierCost rows (chưa ghi sổ) ──────────────────────────────────────
  {
    id: 8,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'SupplierCost',
    docNum: '202501.SupplierCost.ABC1',
    period: '202501',
    currency: 'USD',
    amount: 36560.00,
    xrate: null,
    partnerCode: 'ABC1',
    datasource: 'Platform',
    glPosted: false,
  },
  {
    id: 9,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'SupplierCost',
    docNum: '202501.SupplierCost.ABC2',
    period: '202501',
    currency: 'USD',
    amount: 3656.00,
    xrate: null,
    partnerCode: 'ABC2',
    datasource: 'Platform',
    glPosted: false,
  },
  {
    id: 10,
    comcode: 'ZeniroxPay',
    transdate: '2025-01-31',
    journalType: 'SupplierCost',
    docNum: '202501.SupplierCost.ABC3',
    period: '202501',
    currency: 'USD',
    amount: 14123.00,
    xrate: null,
    partnerCode: 'ABC3',
    datasource: 'Platform',
    glPosted: false,
  },
  // ── Additional months (for filter testing) ────────────────────────────────
  {
    id: 11,
    comcode: 'ZeniroxPay',
    transdate: '2025-02-28',
    journalType: 'Sales of Goods',
    docNum: '202502.Sales of Goods.Individuals',
    period: '202502',
    currency: 'USD',
    amount: 18750.00,
    xrate: null,
    partnerCode: 'Individuals',
    datasource: 'Platform',
    glPosted: false,
  },
  {
    id: 12,
    comcode: 'ZeniroxPay',
    transdate: '2025-02-28',
    journalType: 'ShippingRev',
    docNum: '202502.ShippingRev.Individuals',
    period: '202502',
    currency: 'USD',
    amount: 410.00,
    xrate: null,
    partnerCode: 'Individuals',
    datasource: 'Platform',
    glPosted: false,
  },
  {
    id: 13,
    comcode: 'ZeniroxPay',
    transdate: '2025-02-28',
    journalType: 'SellerCost',
    docNum: '202502.SellerCost.Store1',
    period: '202502',
    currency: 'USD',
    amount: 2100.00,
    xrate: null,
    partnerCode: 'Store1',
    datasource: 'Platform',
    glPosted: false,
  },
  {
    id: 14,
    comcode: 'ZeniroxPay',
    transdate: '2025-02-28',
    journalType: 'SupplierCost',
    docNum: '202502.SupplierCost.ABC1',
    period: '202502',
    currency: 'USD',
    amount: 42000.00,
    xrate: null,
    partnerCode: 'ABC1',
    datasource: 'Platform',
    glPosted: false,
  },
]
