import type { PingPongStagingRow } from '@/lib/types'

export const MOCK_PINGPONG_TRANSACTIONS: PingPongStagingRow[] = [
  // ── Bulk rows (đã ghi sổ) ──────────────────────────────────────────────────
  {
    id: 1,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Incoming Transfer',
    docNum: '202501.Incoming Transfer.Individuals.= STK PINGPONG',
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: 45230.50,
    partnerCode: 'Individuals',
    description: '202501.Incoming Transfer.Individuals',
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: 17432.00,
    datasource: 'BankCAN',
    glPosted: true,
  },
  {
    id: 2,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Monthly Fee',
    docNum: '202501.Monthly Fee.PINGPONG.= STK PINGPONG',
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: -29.99,
    partnerCode: 'PINGPONG',
    description: '202501.Monthly Fee.PINGPONG',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: 17432.00,
    datasource: 'BankCAN',
    glPosted: true,
  },
  // ── Bulk rows (chưa ghi sổ) ────────────────────────────────────────────────
  {
    id: 3,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Outgoing Transfer',
    docNum: '202501.Outgoing Transfer.Individuals.= STK PINGPONG',
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: -18500.00,
    partnerCode: 'Individuals',
    description: '202501.Outgoing Transfer.Individuals',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: 17432.00,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 4,
    comcode: 'ZeniroxPay',
    date: '2025-01-31',
    journalType: 'Currency Exchange',
    docNum: '202501.Currency Exchange.PINGPONG.= STK PINGPONG',
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: 5000.00,
    partnerCode: 'PINGPONG',
    description: '202501.Currency Exchange.PINGPONG',
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: 17432.00,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 5,
    comcode: 'ZeniroxPay',
    date: '2025-01-20',
    journalType: 'Reserve Hold',
    docNum: null,
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: 3200.00,
    partnerCode: null,
    description: null,
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 6,
    comcode: 'ZeniroxPay',
    date: '2025-01-22',
    journalType: 'Reserve Release',
    docNum: null,
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: 1500.00,
    partnerCode: null,
    description: null,
    balanceImpact: 'No Impact',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 7,
    comcode: 'ZeniroxPay',
    date: '2025-01-25',
    journalType: 'Chargeback',
    docNum: null,
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: -850.00,
    partnerCode: null,
    description: null,
    balanceImpact: 'Debit',
    refTxnId: 'PP-2025-0025',
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 8,
    comcode: 'ZeniroxPay',
    date: '2025-01-26',
    journalType: 'Chargeback Reversal',
    docNum: null,
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: 420.00,
    partnerCode: null,
    description: null,
    balanceImpact: 'Credit',
    refTxnId: 'PP-2025-0026',
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 9,
    comcode: 'ZeniroxPay',
    date: '2025-01-28',
    journalType: 'Transaction Fee',
    docNum: null,
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: -125.40,
    partnerCode: null,
    description: null,
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 10,
    comcode: 'ZeniroxPay',
    date: '2025-01-29',
    journalType: 'Withdrawal to Bank',
    docNum: null,
    bankAccountNum: 'STK PINGPONG',
    period: '202501',
    currency: 'CAD',
    amount: -10000.00,
    partnerCode: null,
    description: null,
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: null,
    datasource: 'BankCAN',
    glPosted: false,
  },
  // ── T02/2025 rows (chưa ghi sổ) ───────────────────────────────────────────
  {
    id: 11,
    comcode: 'ZeniroxPay',
    date: '2025-02-28',
    journalType: 'Incoming Transfer',
    docNum: '202502.Incoming Transfer.Individuals.= STK PINGPONG',
    bankAccountNum: 'STK PINGPONG',
    period: '202502',
    currency: 'CAD',
    amount: 52100.00,
    partnerCode: 'Individuals',
    description: '202502.Incoming Transfer.Individuals',
    balanceImpact: 'Credit',
    refTxnId: null,
    refNum: null,
    xrate: 17550.00,
    datasource: 'BankCAN',
    glPosted: false,
  },
  {
    id: 12,
    comcode: 'ZeniroxPay',
    date: '2025-02-28',
    journalType: 'Monthly Fee',
    docNum: '202502.Monthly Fee.PINGPONG.= STK PINGPONG',
    bankAccountNum: 'STK PINGPONG',
    period: '202502',
    currency: 'CAD',
    amount: -29.99,
    partnerCode: 'PINGPONG',
    description: '202502.Monthly Fee.PINGPONG',
    balanceImpact: 'Debit',
    refTxnId: null,
    refNum: null,
    xrate: 17550.00,
    datasource: 'BankCAN',
    glPosted: false,
  },
]
